// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package wireFormater

import (
	"fmt"
	"talk/myAGo/code/service"
)

//START OMIT
// Injectors from container.go:

func CreateApp(config service.Config) (*App, error) {
	formater := DefaultFormater()
	hello := service.New(config, formater)
	app := New(hello)
	return app, nil
}

//END OMIT
// container.go:

type FmtFormater string

func (f FmtFormater) Format(in string) string {
	return fmt.Sprintf(string(f), in)
}

func DefaultFormater() service.Formater {
	return FmtFormater("jméno: %s")
}
