// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package wireTrabl1

import (
	"fmt"
	"talk/myAGo/code/service"
)

// Injectors from container.go:

//START OMIT
func CreateApp(config service.Config) (*App, error) {
	formater := DefaultFormater()
	hello := service.New(config, formater)
	serviceA := NewServiceA(hello)
	serviceB := NewServiceB(hello)
	app := New(serviceA, serviceB)
	return app, nil
}

//END OMIT
// container.go:

type FmtFormater string // HLnew

func (f FmtFormater) Format(in string) string {
	return fmt.Sprintf(string(f), in)
}

func DefaultFormater() service.Formater {
	return FmtFormater("jméno: %s")
}
